"""update_unique_constraints_for_soft_delete

Revision ID: 0cc75a65b392
Revises: d768fa3b3957
Create Date: 2026-02-21 21:58:02.288552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc75a65b392'
down_revision: Union[str, None] = 'd768fa3b3957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_prompt_versions_prompt_ordinal', 'prompt_versions', type_='unique')
    op.create_index('idx_prompt_versions_prompt_ordinal_unique_active', 'prompt_versions', ['prompt_id', 'ordinal'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_prompt_versions_unique_latest', table_name='prompt_versions')
    op.create_index('idx_prompt_versions_unique_latest', 'prompt_versions', ['prompt_id'], unique=True, postgresql_where=sa.text('is_latest = true AND deleted_at IS NULL'))
    op.drop_index('idx_prompts_key', table_name='prompts')
    op.drop_constraint('prompts_key_key', 'prompts', type_='unique')
    op.create_index('idx_prompts_key_unique_active', 'prompts', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompts_key_unique_active', table_name='prompts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('prompts_key_key', 'prompts', ['key'])
    op.create_index('idx_prompts_key', 'prompts', ['key'], unique=False)
    op.drop_index('idx_prompt_versions_unique_latest', table_name='prompt_versions', postgresql_where=sa.text('is_latest = true AND deleted_at IS NULL'))
    op.create_index('idx_prompt_versions_unique_latest', 'prompt_versions', ['prompt_id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_prompt_versions_prompt_ordinal_unique_active', table_name='prompt_versions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('ux_prompt_versions_prompt_ordinal', 'prompt_versions', ['prompt_id', 'ordinal'])
    # ### end Alembic commands ###
