"""Add EvalSummary and Analytics Tables

Revision ID: 22bfe03ccc2c
Revises: h9i0j1k2l3m4
Create Date: 2026-03-05 21:35:21.257781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22bfe03ccc2c'
down_revision: Union[str, None] = 'h9i0j1k2l3m4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_job_meta',
    sa.Column('meta_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('calibration_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['eval_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meta_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('eval_summaries',
    sa.Column('summary_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('total_examples', sa.Integer(), nullable=False),
    sa.Column('scored_examples', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('mean_evaluator_score', sa.Float(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('mean_cost_per_run', sa.Float(), nullable=True),
    sa.Column('cost_per_correct', sa.Float(), nullable=True),
    sa.Column('mean_latency_ms', sa.Float(), nullable=True),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('mce', sa.Float(), nullable=True),
    sa.Column('overconfidence_rate', sa.Float(), nullable=True),
    sa.Column('underconfidence_rate', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['eval_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_eval_summaries_dataset_id', 'eval_summaries', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eval_summaries_dataset_id', table_name='eval_summaries')
    op.drop_table('eval_summaries')
    op.drop_table('eval_job_meta')
    # ### end Alembic commands ###
