"""make_to_version_id_nullable

Revision ID: 999fdeb013cb
Revises: add_cost_usd
Create Date: 2026-02-21 21:07:29.775417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999fdeb013cb'
down_revision: Union[str, None] = 'add_cost_usd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alias_history', 'to_version_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alias_history', 'to_version_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
