"""init

Revision ID: c4e78c22777f
Revises: 
Create Date: 2025-09-06 13:42:54.136719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4e78c22777f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('char_length(key) > 0', name='ck_prompts_key_not_empty'),
    sa.CheckConstraint('char_length(title) > 0', name='ck_prompts_title_not_empty'),
    sa.PrimaryKeyConstraint('prompt_id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_prompts_created_by', 'prompts', ['created_by'], unique=False)
    op.create_index('idx_prompts_key', 'prompts', ['key'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('version_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('model_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('char_length(prompt_text) > 0', name='ck_prompt_versions_text_not_empty'),
    sa.CheckConstraint('ordinal > 0', name='ck_prompt_versions_ordinal_positive'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.prompt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('prompt_id', 'ordinal', name='ux_prompt_versions_prompt_ordinal')
    )
    op.create_index('idx_prompt_versions_created_by', 'prompt_versions', ['created_by'], unique=False)
    op.create_index('idx_prompt_versions_prompt_id_created_at', 'prompt_versions', ['prompt_id', 'created_at'], unique=False)
    op.create_index('idx_prompt_versions_prompt_id_ordinal', 'prompt_versions', ['prompt_id', 'ordinal'], unique=False)
    op.create_index('idx_prompt_versions_unique_latest', 'prompt_versions', ['prompt_id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_versions_unique_latest', table_name='prompt_versions', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_prompt_versions_prompt_id_ordinal', table_name='prompt_versions')
    op.drop_index('idx_prompt_versions_prompt_id_created_at', table_name='prompt_versions')
    op.drop_index('idx_prompt_versions_created_by', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('idx_prompts_key', table_name='prompts')
    op.drop_index('idx_prompts_created_by', table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
