"""add safety pillar soft deletes

Revision ID: c66a3ceadd89
Revises: 35e2b2c3c1b2
Create Date: 2026-04-21 19:24:19.282568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66a3ceadd89'
down_revision: Union[str, None] = '35e2b2c3c1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_examples', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('datasets', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('eval_jobs', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eval_jobs', 'deleted_at')
    op.drop_column('datasets', 'deleted_at')
    op.drop_column('dataset_examples', 'deleted_at')
    # ### end Alembic commands ###
