"""add_deleted_at_to_prompts_and_versions

Revision ID: d768fa3b3957
Revises: 999fdeb013cb
Create Date: 2026-02-21 21:49:34.935317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd768fa3b3957'
down_revision: Union[str, None] = '999fdeb013cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'deleted_at')
    op.drop_column('prompt_versions', 'deleted_at')
    # ### end Alembic commands ###
