"""add_version_soft_delete

Revision ID: 86a5a5bb6200
Revises: bf8dc316c31f
Create Date: 2026-02-01 18:43:29.914947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a5a5bb6200'
down_revision: Union[str, None] = 'bf8dc316c31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_versions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_versions', 'deleted_at')
    # ### end Alembic commands ###
