"""add_soft_delete_v2

Revision ID: bf8dc316c31f
Revises: c4e78c22777f
Create Date: 2026-02-01 18:31:14.077694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8dc316c31f'
down_revision: Union[str, None] = 'c4e78c22777f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('prompts_key_key', 'prompts', type_='unique')
    op.create_index('idx_prompts_key', 'prompts', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompts_key', table_name='prompts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('prompts_key_key', 'prompts', ['key'])
    op.drop_column('prompts', 'deleted_at')
    # ### end Alembic commands ###
